version: '3'

services:
  cafeshop:
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres_cafeshop

  postgres_cafeshop:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - '5454:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}

